#pragma once

// Cosmos
#define EE_HANDS

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET

#define SPLIT_USB_DETECT
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_PIN_SWAP
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

// QMK
#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define SPECULATIVE_HOLD
